# Generated by Django 6.0.5 on 2026-05-25 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel/Procurement'), ('utility', 'Utility/Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1'), ('scope2', 'Scope 2'), ('scope3', 'Scope 3')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('raw_quantity', models.FloatField()),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_quantity', models.FloatField()),
                ('normalized_unit', models.CharField(default='kg_co2e', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('emission_factor', models.FloatField(blank=True, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=100)),
                ('co2e_kg', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('flag_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_note', models.TextField(blank=True)),
                ('locked_for_audit', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ingested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingested_records', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='accounts.organisation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
    ]
